### PR TITLE
Joints jogging and fix for overshoot problem

### PR DESCRIPTION
**Pull request by machinekoder**
This patch adds joint jogging. For this purpose I reused the [jog_msgs from jog_control](https://github.com/tork-a/jog_control). Joint jogging works exactly like Cartesian jogging, calculations are just a lot simpler.

Additionally, this patch also contains a fix for the overshooting problem. At the end of each jog move (when the user releases the move button and the incoming command messages stop) a new message with zero velocity and the last comand joint positions is attached.

To separate the jog_msgs package correctly, I have moved the jog_arm core code into a subdirectory, making this repository home of multiple ROS package. That should be the easiest way for user to use this package as long as jog_msgs isn't released on it's own.

### CODE REVIEW

**Comment by AndyZe** [comment]
Looks good! I'd eventually like a test program for this joint jogging. I can write that if you don't. I would probably use the keyboard.

**Comment by AndyZe** [comment]
I added code for joint jogging to the XBox and Spacenav demos. It works great.

**Comment by machinekoder** [comment]
Awesome, great to hear!

**Comment by AndyZe** [comment]
I should have asked earlier, but what is the point of the parameter publish_delay? Were you having network timing issues?

**Comment by machinekoder** [comment]
The `publish_delay` was added because the start of the motion must be after the current time. So the `publish_delay` is basically a time offset added to every message. I don't have any message delay locally, but still, the first trajectory point was always skipped.

**Pull request merged**
